import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * 侧边栏：按「篇 → 章」组织，使用 autogenerated + 目录位置排序
 */
const sidebars: SidebarsConfig = {
  tutorial: [
    {
      type: 'category',
      label: '开始',
      items: ['intro/what-is-agent'],
    },
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
}

export default sidebars
